sudo: required

services:
  - docker

before_install:
  # Setup your application stack. You may need to tweak these commands if you
  # doing out-of-the-ordinary docker-compose builds.
  - docker-compose up -d

  # You will want this for logging. If one of your containers does not build for
  # whatever reason it's best to report that now before your tests start
  # otherwise it can be really tricky to debug why tests are failing sometimes.
  - docker ps

  # This is just our script to setup all the database tables and other fixtures
  # we need. You should remove this if it's not necessary or you have other
  # scripts handling this.
  #- docker/web/provision.sh

  - docker build -t uwegerdes/frontend-development .

script:
  - docker run --rm --network="$(docker inspect --format='{{.HostConfig.NetworkMode}}' fd-nginx)" --add-host dockerhost:$(docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}} {{end}}' fd-nginx) uwegerdes/frontend-development npm test
