# To execute this docker-compose yml file use docker-compose -f <file_name> up
# Add the "-d" flag at the end for deattached execution
version: "3.5"

services:
  fd-e2e-mysql:
    build:
      context: https://github.com/UweGerdes/docker-mysql.git
      args:
        - MYSQL_ROOT_PASSWORD=123456
    image: uwegerdes/mysql
    container_name: fd-e2e-mysql
    hostname: mysql
    volumes:
      - ./build/mysql:/entrypoint-initdb.d

  fd-e2e-mail:
    build:
      context: https://github.com/UweGerdes/docker-mail.git
    image: uwegerdes/mail
    container_name: fd-e2e-mail
    hostname: mail

  fd-e2e-php-fpm:
    build:
      context: https://github.com/UweGerdes/docker-php-fpm.git
    image: uwegerdes/php-fpm
    container_name: fd-e2e-php-fpm
    hostname: php-fpm
    volumes:
      - ./htdocs:/var/www/htdocs
    links:
      - fd-e2e-mysql:mysql
      - fd-e2e-mail:mail.local

  fd-e2e-nginx:
    build:
      context: https://github.com/UweGerdes/docker-nginx.git
    image: uwegerdes/nginx
    container_name: fd-e2e-nginx
    hostname: nginx
    ports:
      - "51289:80"
    links:
      - fd-e2e-php-fpm:php-fpm
    volumes:
      - ./build/nginx/sites-available:/etc/nginx/sites-available
      - ./htdocs:/var/www/htdocs

  fd-e2e-hub:
    image: selenium/hub
    container_name: fd-e2e-hub
    hostname: fd-e2e-hub

  fd-e2e-chrome:
    image: selenium/node-chrome
    container_name: fd-e2e-chrome
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - fd-e2e-hub
    environment:
      HUB_HOST: fd-e2e-hub
      HUB_PORT: 4444
      JAVA_OPTS: -Dselenium.LOGGER.level=WARNING
    links:
      - fd-e2e-nginx:nginx

  fd-e2e-firefox:
    image: selenium/node-firefox
    container_name: fd-e2e-firefox
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - fd-e2e-hub
    environment:
      HUB_HOST: fd-e2e-hub
      HUB_PORT: 4444
      JAVA_OPTS: -Dselenium.LOGGER.level=WARNING
    links:
      - fd-e2e-nginx:nginx

  fd-e2e-frontend:
    image: uwegerdes/e2e-workflow
    container_name: fd-e2e-frontend
    hostname: fd-e2e-frontend
    ports:
      - 51287:8080
      - 51288:8081
    depends_on:
      - fd-e2e-hub
    environment:
      HUB_HOST: fd-e2e-hub
      HUB_PORT: 4444
      NODE_ENV: staging
      LIVERELOAD_PORT: 51288
    volumes:
      - ./tests/e2e-workflow:/home/node/app/config/modules/fd/tests/e2e-workflow
      - ./tests/e2e-workflow/results:/home/node/app/results/config/modules/fd/tests/e2e-workflow
    command: npm run dev
