# To execute this docker-compose yml file use docker-compose -f <file_name> up
# Add the "-d" flag at the end for deattached execution
version: "3.5"

services:
  fd-mysql:
    build:
      context: https://github.com/UweGerdes/docker-mysql.git
      args:
        - MYSQL_ROOT_PASSWORD=123456
    image: uwegerdes/mysql
    container_name: fd-mysql
    hostname: mysql
    volumes:
      - ./build/mysql:/entrypoint-initdb.d

  fd-mail:
    build:
      context: https://github.com/UweGerdes/docker-mail.git
    image: uwegerdes/mail
    container_name: fd-mail
    hostname: mail

  fd-php-fpm:
    build:
      context: https://github.com/UweGerdes/docker-php-fpm.git
    image: uwegerdes/php-fpm
    container_name: fd-php-fpm
    hostname: php-fpm
    volumes:
      - ./htdocs:/var/www/htdocs
    links:
      - fd-mysql:mysql
      - fd-mail:mail.local

  fd-nginx:
    build:
      context: https://github.com/UweGerdes/docker-nginx.git
    image: uwegerdes/nginx
    container_name: fd-nginx
    hostname: nginx
    ports:
      - "51289:80"
    links:
      - fd-php-fpm:php-fpm
    volumes:
      - ./build/nginx/sites-available:/etc/nginx/sites-available
      - ./htdocs:/var/www/htdocs
