version: '2'
services:
  baseimage:
    build:
      context: https://github.com/UweGerdes/docker-baseimage.git
      args:
        - APT_PROXY
        - TZ
    image: uwegerdes/baseimage
    container_name: baseimage

  data:
    build:
      context: https://github.com/UweGerdes/docker-data.git
    image: uwegerdes/data
    container_name: data
    volumes:
      - ./htdocs:/var/www/htdocs

  mysql:
    build:
      context: https://github.com/UweGerdes/docker-mysql.git
      args:
        - MYSQL_ROOT_PASSWORD=123456
    image: uwegerdes/mysql
    container_name: mysql
    volumes:
      - ./src/mysql:/entrypoint-initdb.d

  mail:
    build:
      context: https://github.com/UweGerdes/docker-mail.git
    image: uwegerdes/mail
    container_name: mail

  php-fpm:
    build:
      context: https://github.com/UweGerdes/docker-php-fpm.git
    image: uwegerdes/php-fpm
    container_name: php-fpm
    volumes_from:
      - data
    links:
      - mysql
      - mail:mail.local

  nginx:
    build:
      context: https://github.com/UweGerdes/docker-nginx.git
    image: uwegerdes/nginx
    container_name: nginx
    ports:
      - "3080:80"
    volumes_from:
      - data
      - php-fpm
